
import path from 'path'
import { fs } from '../utils'

async function SitemapGenerator(context) {
  const { blogUrl } = context.blog
  const { publicPath } = context.system

  let sxml =`<?xml version="1.0" encoding="UTF-8"?>
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
    http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<!-- generated by hanejs -->`
  for (const post of context.posts) {
    sxml += `
<url>
  <loc>${blogUrl}${post.url}</loc>
  <lastmod>${post.updateTime}</lastmod>
</url>`
  }

  for (const page of context.pages) {
    sxml += `
<url>
  <loc>${blogUrl}${page.url}</loc>
  <lastmod>${page.updateTime}</lastmod>
</url>`
  }

  sxml += `
</urlset>
`
  await fs.writeFileAsync(path.join(publicPath, 'sitemap.xml'), sxml)
  return context
}

export default SitemapGenerator
